---
# config file for pre-commit
default_stages: [commit, push]
exclude: 'README.md|docs/|docs_dev/system/originals/|.pre-commit-config.yaml|published_samples/src/'
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: \.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs, --no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [types-requests, types-PyYAML]
        exclude:
          (^unpublished_samples/|^tests/.*/src|^tests_old/.*/src)
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        entry: flake8 --max-line-length=100
        files: \.py$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        name: Check yaml files with yamllint
        entry: yamllint -c .github/linters/.yaml-lint.yml
        types: [yaml]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        entry: isort --settings-path .github/linters/.isort.cfg
        name: Run isort to sort imports
        description: "Sorts python imports"
        files: \.py$
  - repo: local
    hooks:
      - id: markdownlint
        name: Run markdownlint
        description: "Checks the style of Markdown files."
        entry: markdownlint --config .github/linters/.markdown-lint.yml
        language: node
        types: [markdown]
        files: \.(md|mdown|markdown)$
        additional_dependencies: ['markdownlint-cli']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer