name: Artifact

on: 
  push:
    branches:
      - 'feature'
  # pull_request:
  #   branches:
  #     - 'develop'

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Test App Code
        run: pytest -sv --html ./report/report.html
        shell: bash

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./report

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
        


