name: CI

on: 
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:
    
jobs:
  timestamp:
    outputs:
      now: ${{ steps.timestamp.outputs.now }}
    runs-on: ubuntu-latest
    steps:
      - id: timestamp
        run: echo "now=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
  test:
    needs: timestamp
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: ['3.8']
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          echo ${timestamp}
        env:
          timestamp: ${{ needs.timestamp.outputs.now }}
        
      - name: Test App Code
        run: pytest -sv --html ./report/index.html

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./report

      - name: Deploy
        if: github.ref_name == 'develop' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report