name: Dispatch

on:
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'Log level'
    #     required: true
    #     default: 'warning'
    #     type: choice
    #     options:
    #     - info
    #     - warning
    #     - debug
    #   tags:
    #     description: 'Test scenario tags'
    #     required: false
    #     type: boolean  # 类型 boolean、choice、number 或 string
  schedule:
    - cron: '*/5 * * * *'

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: ${{ github.ref }}"

        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
      - uses: ./.github/actions/test_main
        with:
          TEST_STRING: "hello world test string"
          
